### ISSUE TITLE
Portable Media Review - By Sanchita and Raghupati-FirstReview

### ISSUE THREAD

**Issue by sanchita-dixit** [openedx-vlead/portable-media#3]
Review on 8th Nov, 2016
The below comments incorporate the modifications required in the Bootstrapping document for the Cluster setup : 

1) Move /vz to a partition where there is enough space - Please mention this as an optional step.

2) The cluster setup section in the Github design document - Please mention the cluster name (so that we always give one common name to the cluster)

3) Please mention the creation of eth0 and eth1 interfaces for ansible server in the boostrapping document.

4) *Install openssh if not installed* section should be before *Enable ssh access from localhost to localhost and router using key-based authentication* step.

5) Mention the steps for  Copy ssh public keys of vlead user to systems-model repository in bitbucket. 
Steps followed while rebview : login as admin in bitbucket << go to sytems-model repo << go to settings << add ansible public key in the deployment keys section << then clone the systems-model repository inside 'vlead' user home directory. 

6) In the router configuration if nslookup command not found, include bind-utils installation in the router.yml playbook by using the yum package.

7) In the router configuration : *nslookup (nslookup router.[{cluster}.].vlabs.ac.in <router-public-ip>)* command is not mandatory to be run. Could be marked as optional.

8) In the ADS server configuration the step *command="hooks.sh",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty <public_key>* (mention the ADS public key in <public_key>, change <public-key> to <public_key>), some places it is written <public_key> and somewhere <public-key>, please use only one notation to avoid confusion.

Review on 9th Nov, 2016

9) Our General understanding on the SSH key based actions:
We are putting the public key of the Ansible server (vlead user not of root user since we have cloned the systems-model repo in the vlead user and all the playbooks are present there only) into the cluster servers as well any other server which is outside the cluster. 

10) In the DNS service configuration
a) The step of Enable SSH access to root account from config-server (needs more clarity or more description of the step).
b) In the portable media setup : nagios_server, nagios_client, rsnapshot_server, rsnapshot_client, ossec_server and ossec_client should be commented out in every playbook since we are not going to use them. This step should be kept in mind very carefully.
c) The step : - *Comment =ossec_client= and uncomment =rsnapshot_client= in all servers playbook*, should be *comment out both* for portable media.
d) Since we are setting up a separate DNS server which is not a part of the cluster, but we are using public_dns.yaml playbook for running the ansible playbook for this server as well, it will try to set up the gateway as 10.100.1.1 which would throw error as our DNS is not a part of the cluster. To solve this problem, we need to comment out the default gateway lines from the roles/common/tasks/main.yml file in the ansible sever. Below lines should be commented :
<pre>
#- name: setting the default gw, skips if router or ansible server
#  shell: route del default; route add default gw {{router_internal_ip}}
#  when: not ( i_ans is defined or i_router is defined )
#  ignore_errors: yes
#
#- name: make this route persistent after reboot
#  lineinfile: line="route del default; route add default gw {{router_internal_ip}}" destfile=/etc/rc.local state=present regexp="route *"
#  when: not ( i_ans is defined or i_router is defined )
</pre>
e) The step - *Add these entries in /var/named/virtual-labs.ac.in.forward and /var/named/vlabs.ac.in.forward* should be *Add these entries in /var/named/{cluster}.virtual-labs.ac.in.forward and /var/named/{cluster}.vlabs.ac.in.forward*.

Review on 10th Nov, 2016

11) Install OpenVZ web console
Change the vim owl/installer/ai.sh with DOWNLOAD link should be (https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/ovz-web-panel/ovz-web-panel-2.4.tgz)

12) Open edX platform installation 
a) Please do yum install vzkernel-devel while running through step : Install VirtualBox 4.3.12 (i386) or later  and then run /sbin/vboxconfig 
 b) No need to do these steps in CentOs : Install other dependencies if there are any (sudo apt-get install -f) , install other requirements (sudo apt-get install virtualbox-dkms virtualbox-guest-dkms)
c) Replace apt-get with yum while doing installations for centos machine. 
d) Change IP of DNS service and Openedx     
e) Chkconfig NetworkManager off and Chkconfig network on in bootstrapping process

Review on 15th Nov, 2016

13) Wireless router configuration (Since these steps are not detailed in the document, while reviewing we followed the below steps:)
a) All the modifications have to be made only in the LAN settings (192.168.2.1 - UI console for router)
b) 4 fields are to be modified : IP Address, Starting pool address, Ending pool address and Local Domain Name. IP Address has to be anything like 10.2.57.1,10.2.57.2 or 10.2.57.3 etc. In the documentation, it is mentioned the range to be 10.2.57.0/24 but the IP should never be 10.2.57.0 or 10.2.57.24
c) Starting pool address should be 10.2.57.2 if you have already assigned the IP as 10.2.57.1 and the ending pool address should be 10.2.57.253 (253 users).
d) Replace the Local Domain Name field with 10.2.57.64 (Local DNS Server IP)

14) Configure-server
In the ansible-server as vlead user in the systems-model/build/edx/roles/common_vars/vars/main.yml should be changed from (is_amazon: "no") to (is_amazon: "yes").

**Comment by sivashankerN** [comment]
Incorporated the changes based on the review done by Raghupathi and Sanchita.  

Need to make changes that are  updated on "15th Nov, 2016"

**Comment by kraghupathi** [comment]
**Wireless router configuration**
- Wireless router configuration (Since these steps are not detailed in the document, while reviewing we followed the below steps:)
  + All the modifications have to be made only in the LAN settings
    (192.168.2.1 - UI console for router) 4 fields are to be
    modified : IP Address, Starting pool address, Ending pool address
    and Local Domain Name. IP Address has to be (10.x.x.x). In the documentation, it is mentioned the range to be 10.2.57.0/24 (which means 0/24 is subnet of IP)
  + Starting pool address should be (10.x.x.2) and the ending pool address should be (10.x.x.253) (which means upto 253 users can connect wifi router)
  + Replace the Local Domain Name field *Belkin* with 10.2.57.64 (Local DNS Server IP)

**Configure-server**

- Follow the below steps in ansible-server using vlead user

`vim systems-model/build/edx/roles/common_vars/vars/main.yml`

- In above file change the line, which is (is_amazon: "no") to (is_amazon: "yes")

**Changing dns IP in localhost(base machine)**

- User can access the labs through LAN cable and also over wireless.
- Once the user is connected to wireless or LAN, user has to modify their DNS servers follow the below steps

`sudo vim /etc/resolv.conf`

Delete existing entries and add the following line

`nameserver 10.2.57.64`

- Once the users got connected to wifi, user has to unset proxy if any proxies used previously( Set No Proxy) in their browsers and their systems,  follow the below steps
- *For browser*

`Firefox --> Preferences --> Advanced --> Network --> Settings `

**Comment by sivashankerN** [comment]
@sanchita-dixit @kraghupathi .  Thanks for reviewing portable media implementation and giving some suggestions for improving documentation  

Please see the User manual  for Wifi -router configuration which is all ready updated.
Please note that the Wi-Fi router configuration may vary from router to router

**Comment by sivashankerN** [comment]
Updated the document based on feedback given by Sanchita and Raghupathi, 

@sanchita-dixit  Please close this issue
